### ISSUE TITLE
[empty locale] Autocomplete gets added after the prompt when using starship

### ISSUE THREAD

**Issue by Ultra980** [akinomyoga/ble.sh#269]
**ble version**: 0.4.0-devel3+e3cdb9d 
**Bash version**: 5.2.15(1)-release (x86_64-suse-linux) 

**Output of `[Ctrl-X] [Ctrl-V]`**:
* In the distrobox:
```
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux) [openSUSE Tumbleweed]
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.39.0, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:37a0fec4e27779dc87253aa7f27cfa8d14d6a4a6, 77846 bytes) (noarch)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale:
terminal: TERM=xterm-256color wcwidth=4.1-west/15.0-2+ri, xterm:115 (1;115;0)
```

* On bare metal:
``` 
GNU bash, version 5.2.15(1)-release (x86_64-suse-linux) [openSUSE MicroOS]
ble.sh, version 0.4.0-devel3+e3cdb9d (noarch) [git 2.39.0, GNU Make 4.4, GNU Awk 5.2.1, API 3.2, PMA Avon 8-g1, (GNU MPFR 4.1.1-p1, GNU MP 6.2.1)]
bash-completion, version 2.11 (hash:37a0fec4e27779dc87253aa7f27cfa8d14d6a4a6, 77846 bytes) (noarch)
starship, version 1.12.0-master (rustc 1.65.0 (897e37553 2022-11-02), 2022-12-13 16:12:30 +00:00)
locale: LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8
terminal: TERM=xterm-256color wcwidth=15.0-musl/15.0-2+ri, xterm:115 (1;115;0)
```

When I type a command into the prompt, if it has suggestions for completing the command they get put after the prompt. For example, if I type `ca` ble.sh tries to autocomplete with `cat` but it adds `cat` after the already written command, resulting in `cacat`. I would send a recording with `asciinema`, but the issue seems to go away when I start recording (with `asciinema rec error.cast`). 
This only happens when I'm inside a `distrobox` container, not on the host system.
I don't know if this is related, but I'm using the [starship](https://starship.rs) prompt with the following config:

```toml
format = """
[ ](bg:#4ab0bb)\
[ ](bg:#5bc0cc)\
[ ](bg:#6cd0dd)\
[ ](bg:#7de0ee)\
[   ](bg:#8ef0ff fg:#090c0c)\
[](bg:#1692a4 fg:#8ef0ff)\
$directory\
[](fg:#1692a4 bg:#006d7d)\
$git_branch\
$git_status\
[](fg:#006d7d bg:#004b5b)\
$container\
[](fg:#004b5b bg:#003a4a)\
$sudo\
[](fg:#003a4a bg:#003740)\
$nodejs\
$rust\
$golang\
$php\
$python\
[](fg:#003740 bg:#00171b)\
$time\
$status\
[ ](fg:#00171b)
[ ](bg:#4ab0bb)\
[](fg:#5bc0cc)  """

[directory]
style = "fg:#bef6ff bg:#1692a4"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "fg:#1692a4 bg:#006d7d"
format = '[[ $symbol $branch ](fg:#1692a4 bg:#006d7d)]($style)'

[git_status]
style = "fg:#1692a4 bg:#006d7d"
format = '[[($all_status$ahead_behind )](fg:#1692a4 bg:#006d7d)]($style)'

[nodejs]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[rust]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[php]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[python]
symbol = ""
style = "bg:#003740"
format = '[[ $symbol ($version) ](fg:#1692a4 bg:#003740)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#00171b"
format = '[[  $time ](fg:#bef6ff bg:#00171b)]($style)'

[container]
symbol = ""
style = "fg:#bef6ff bg:#004b5b"
format = '[ $symbol $name ]($style)'

[status]
disabled = false
style = "bg:#00171b"
success_symbol = '[](fg:#00ff00 bg:#00171b)'
symbol = '[](fg:#ff0000 bg:#00171b)'
format = "[ $symbol $status ]($style)"

[sudo]
symbol = ""
style = "bg:#003b4b"
format = "[ $symbol ]($style)"
disabled = false
```
